#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/jenkins

- name: Install dependencies
  yum:
    name:
      - git
      - docker
      - java-17-amazon-corretto
    state: present

- name: Start and enable Docker
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Add Jenkins repo
  get_url:
    url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo

- name: Import Jenkins key
  rpm_key:
    key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key
    state: present

- name: Install Jenkins
  yum:
    name: jenkins
    state: present

- name: Start and enable Jenkins
  systemd:
    name: jenkins
    state: started
    enabled: yes

